version: 2
registries:
  python-index-ezcater-jfrog-io-ezcater-api-npm-npm:
    type: python-index
    url: https://ezcater.jfrog.io/ezcater/api/npm/npm
    username: "${{secrets.PYTHON_INDEX_EZCATER_JFROG_IO_EZCATER_API_NPM_NPM_USERNAME}}"
    password: "${{secrets.PYTHON_INDEX_EZCATER_JFROG_IO_EZCATER_API_NPM_NPM_PASSWORD}}"

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: singer-python
    versions:
    - 5.10.0
    - 5.11.0
    - 5.12.0
    - 5.9.1
  registries:
  - python-index-ezcater-jfrog-io-ezcater-api-npm-npm
